######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 30 14:15:42 2012
######################################################################

QT+=network
TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += ui_mainwindow.h
SOURCES += debug/qrc_qrc_mainwindow.cpp
